apiVersion: apps/v1
kind: Deployment
metadata : 
  name: movies
spec:
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: efcarrera/rotten-patatoes:4
          ports:
            - containerPort: 5000

---
  
apiVersion: v1
kind: Service
metadata: 
  name: movies-service
spec: 
  selector:
    app: movies
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
